// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: api/pulse.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	LogLevel      string                 `protobuf:"bytes,3,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	RequestMsg    string                 `protobuf:"bytes,4,opt,name=request_msg,json=requestMsg,proto3" json:"request_msg,omitempty"`
	LatencyMs     float64                `protobuf:"fixed64,5,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_api_pulse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pulse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_api_pulse_proto_rawDescGZIP(), []int{0}
}

func (x *LogRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *LogRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *LogRequest) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

func (x *LogRequest) GetRequestMsg() string {
	if x != nil {
		return x.RequestMsg
	}
	return ""
}

func (x *LogRequest) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *LogRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ResponseMsg   string                 `protobuf:"bytes,2,opt,name=response_msg,json=responseMsg,proto3" json:"response_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_api_pulse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pulse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_api_pulse_proto_rawDescGZIP(), []int{1}
}

func (x *LogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LogResponse) GetResponseMsg() string {
	if x != nil {
		return x.ResponseMsg
	}
	return ""
}

var File_api_pulse_proto protoreflect.FileDescriptor

const file_api_pulse_proto_rawDesc = "" +
	"\n" +
	"\x0fapi/pulse.proto\x12\bpulse.v1\"\xc9\x01\n" +
	"\n" +
	"LogRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x1b\n" +
	"\tlog_level\x18\x03 \x01(\tR\blogLevel\x12\x1f\n" +
	"\vrequest_msg\x18\x04 \x01(\tR\n" +
	"requestMsg\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x05 \x01(\x01R\tlatencyMs\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"J\n" +
	"\vLogResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fresponse_msg\x18\x02 \x01(\tR\vresponseMsg2F\n" +
	"\fPulseService\x126\n" +
	"\aSendLog\x12\x14.pulse.v1.LogRequest\x1a\x15.pulse.v1.LogResponseB\"Z codeberg.org/Wislow/pulse/api;pbb\x06proto3"

var (
	file_api_pulse_proto_rawDescOnce sync.Once
	file_api_pulse_proto_rawDescData []byte
)

func file_api_pulse_proto_rawDescGZIP() []byte {
	file_api_pulse_proto_rawDescOnce.Do(func() {
		file_api_pulse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_pulse_proto_rawDesc), len(file_api_pulse_proto_rawDesc)))
	})
	return file_api_pulse_proto_rawDescData
}

var file_api_pulse_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_pulse_proto_goTypes = []any{
	(*LogRequest)(nil),  // 0: pulse.v1.LogRequest
	(*LogResponse)(nil), // 1: pulse.v1.LogResponse
}
var file_api_pulse_proto_depIdxs = []int32{
	0, // 0: pulse.v1.PulseService.SendLog:input_type -> pulse.v1.LogRequest
	1, // 1: pulse.v1.PulseService.SendLog:output_type -> pulse.v1.LogResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_pulse_proto_init() }
func file_api_pulse_proto_init() {
	if File_api_pulse_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_pulse_proto_rawDesc), len(file_api_pulse_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_pulse_proto_goTypes,
		DependencyIndexes: file_api_pulse_proto_depIdxs,
		MessageInfos:      file_api_pulse_proto_msgTypes,
	}.Build()
	File_api_pulse_proto = out.File
	file_api_pulse_proto_goTypes = nil
	file_api_pulse_proto_depIdxs = nil
}
