// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: api/pulse.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PulseService_SendLog_FullMethodName = "/pulse.v1.PulseService/SendLog"
)

// PulseServiceClient is the client API for PulseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PulseServiceClient interface {
	SendLog(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error)
}

type pulseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPulseServiceClient(cc grpc.ClientConnInterface) PulseServiceClient {
	return &pulseServiceClient{cc}
}

func (c *pulseServiceClient) SendLog(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, PulseService_SendLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PulseServiceServer is the server API for PulseService service.
// All implementations must embed UnimplementedPulseServiceServer
// for forward compatibility.
type PulseServiceServer interface {
	SendLog(context.Context, *LogRequest) (*LogResponse, error)
	mustEmbedUnimplementedPulseServiceServer()
}

// UnimplementedPulseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPulseServiceServer struct{}

func (UnimplementedPulseServiceServer) SendLog(context.Context, *LogRequest) (*LogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendLog not implemented")
}
func (UnimplementedPulseServiceServer) mustEmbedUnimplementedPulseServiceServer() {}
func (UnimplementedPulseServiceServer) testEmbeddedByValue()                      {}

// UnsafePulseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PulseServiceServer will
// result in compilation errors.
type UnsafePulseServiceServer interface {
	mustEmbedUnimplementedPulseServiceServer()
}

func RegisterPulseServiceServer(s grpc.ServiceRegistrar, srv PulseServiceServer) {
	// If the following call panics, it indicates UnimplementedPulseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PulseService_ServiceDesc, srv)
}

func _PulseService_SendLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PulseServiceServer).SendLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PulseService_SendLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PulseServiceServer).SendLog(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PulseService_ServiceDesc is the grpc.ServiceDesc for PulseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PulseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pulse.v1.PulseService",
	HandlerType: (*PulseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendLog",
			Handler:    _PulseService_SendLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/pulse.proto",
}
